### ISSUE TITLE
Admonitiions styling should match Spring Reference

### ISSUE THREAD

**Issue by rwinch** [rwinch/antora-ui-spring#5]
The current styling for [admonitions](https://docs.antora.org/antora/2.3/asciidoc/admonitions/#admonition-styles) does not match the reference documentation styling.

Using `gulp preview` in antora-ui-spring will render a document that shows a sample of all the admonitions:

![image](https://user-images.githubusercontent.com/362503/128728678-cb7bada7-d27a-4809-8b41-ce8d4f2b5f86.png)

You can see this differs from the admonitions in Spring Documentation. An example can be found in the [Boot Reference](https://docs.spring.io/spring-boot/docs/2.5.x/reference/html/upgrading.html#upgrading.to-feature):

![image](https://user-images.githubusercontent.com/362503/128729270-7fdf2efe-5405-4818-8615-466479b76417.png)

**Comment by philwebb** [comment]
CSS for the current versions used by Boot is [here](https://github.com/spring-io/spring-asciidoctor-backends/blob/4c77f3145aeef4c318fc33ae859e6917a4dc82c2/src/main/css/asciidoctor.css#L358) if it helps.

**Comment by rwinch** [comment]
It appears this was fixed in 5147f2ee23faeadf058a6ab41677c54019606db2 See below for the updated styling


![admon](https://user-images.githubusercontent.com/362503/134540955-e3077717-6bf5-4e70-a678-523c3e2ca281.png)
